class DeviceDataQueries {
  static String getAllUserDevices({int nDeviceCount, int nEventCount}) {
    return r'''
      query AllUserDevicesInfo($nDeviceCount: Int, $nEventCount: Int) {
        devices(first: $nDeviceCount){
          edges{
            cursor
            node{
              imei
              unitName
              unitAdminName
              unitAdminPhoneNumber
              unitLocation{
                suburb
                city
              }
              ch1On
              ch2On
              ch3On
              ch4On
              ch5On
              ch1Name
              ch2Name
              ch3Name
              ch4Name
              ch5Name
              alertStateCh1
              alertStateCh2
              alertStateCh3
              alertStateCh4
              alertStateCh5
              upperThresholdCh1
              upperThresholdCh2
              upperThresholdCh3
              upperThresholdCh4
              upperThresholdCh5
              lowerThresholdCh1
              lowerThresholdCh2
              lowerThresholdCh3
              lowerThresholdCh4
              lowerThresholdCh5
              monitoringActiveCh1
              monitoringActiveCh2
              monitoringActiveCh3
              monitoringActiveCh4
              monitoringActiveCh5
              ch1MasksAlerts
              ch2MasksAlerts
              ch3MasksAlerts
              ch4MasksAlerts
              ch5MasksAlerts
              unitsCh1
              unitsCh2
              unitsCh3
              unitsCh4
              unitsCh5
              zeroOffsetCh1
              zeroOffsetCh2
              zeroOffsetCh3
              zeroOffsetCh4
              zeroOffsetCh5
              scaleFactorCh1
              scaleFactorCh2
              scaleFactorCh3
              scaleFactorCh4
              scaleFactorCh5
              ch1SensorType
              ch2SensorType
              ch3SensorType
              ch4SensorType
              ch5SensorType
              eventSet(first: $nEventCount){
                edges{
                  node{
                    ch1
                    ch2
                    ch3
                    ch4
                    ch5
                    deviceTimeDate
                  }
                }
                pageInfo{
                  hasNextPage
                  hasPreviousPage
                  startCursor
                  endCursor
                }
              }
            }
          }
        }
      }
    ''';
  }
}
